### ISSUE TITLE
Android javadoc and source support in vim

### ISSUE THREAD

**Issue by yoshi1123** [hsanson/vim-android#102]
Create android library to use with vim with javadoc and goto-definition support:

1.
Run this script (set `MAVEN_REPO_DIR` and `ANDROID_VERSION` appropriately): #[https://gist.github.com/yoshi1123/9ccd7af1e5cdfec177bc54b2073234be](https://gist.github.com/yoshi1123/9ccd7af1e5cdfec177bc54b2073234be) (you can select no for the second question about creating a gradle cache for android-lib).

This will create a local maven repository as such:
```
#   maven-repo
#   └── com
#       └── android
#           └── android-lib
#               └── 29
#                   ├── android-lib-29.jar
#                   ├── android-lib-29.pom
#                   ├── android-lib-29-sources.jar
#                   └── maven-metadata.xml
```

2.
Create a .classpath: `:GradleGenClassPathFile` (via vim-android).

3.
Add this to `.classpath`:
```
    <classpathentry exported="true" kind="lib" path="/path/to/maven-repo/com/android/android-lib/29/android-lib-29.jar" sourcepath="/path/to/maven-repo/com/android/android-lib/29/android-lib-29-sources.jar"/>
```
And uncomment any android.jar and android source classpath entries.

4.
Use a vim LSP plugin for jar goto-definition support with eclipse-jdt-ls. (For ALE, I submitted a PR #[https://github.com/dense-analysis/ale/pull/4030](https://github.com/dense-analysis/ale/pull/4030) to support goto-definition for jar files, such as the ones in step 1).

(NOTE: I am not aware of any vim LSP plugins with support for java-language-server goto-definition methods for jar files. Though, to use the library in step one in java-language-server, use this as the java-language-server config:
```
        \    'workspace_config': {
        \      'java': {
        \	     'externalDependencies': [
        \ 	       'android:androidsrc:29',
        \	     ]
        \      }
```
For java-language-server to recognize the library, select 'y' to the "Create gradle cache for android-lib?" question in the script in step 1. This will create a gradle cache for android-lib as such:
```
#   ~/.gradle/caches/modules-2/files-2.1/com.android/android-lib
#   └── 29
#       ├── 5c7191460a18e363e62d3594b85976a7d9314fb7
#       │   └── android-lib-29.jar
#       └── 9251decef80e5988df2abe0284c218dd7bcdb6cb
#           └── android-lib-29-sources.jar
```
)

**Comment by hsanson** [comment]
Using latest ALE with jdturi support and latest version of this plugin with eclipselsp integration (#99) the ALEGotToDefinition works fine for Android core classes (e.g. Activity) and generated ones (e.g. R).   I think this issue is no longer needed?
