### ISSUE TITLE
AndroidLaunch command failing

### ISSUE THREAD

**Issue by sultanahamer** [hsanson/vim-android#103]
I have installed the plugin and am loving the ease of setup.

One problem I have faced is that, I am not able to launch the application with `AndroidLaunch debug` command.

After I debugged, I have found the issue

` let l:mainId = system(aapt#bin() . ' list -a ' . l:apk . ' | sed -n "/^Package Group[^s]/s/.*name=//p"  | sed "s/$/ 1/" ')`

This command was trying to identify the package name of the app. And the aapt#bin() function has code to search for either aapt2 or aapt.

The problem here is that aap2 and aapt has different cli commands.

To get info from aapt2, we have to use `dump badging` instead of `list -a`

 `./aapt2 dump badging ~/**/app/build/outputs/apk/debug/app-debug.apk`

For aapt, the `list -a` works as expected.

The output also differs a lot. So the sed part also has to be changed for aapt2. Here is output line you might want to target from aapt2

`package: name='opencontacts.open.com.opencontacts.debug' versionCode='23' versionName='23.0' platformBuildVersionName='12' platformBuildVersionCode='31' compileSdkVersion='31' compileSdkVersionCodename='12'
`

As a work around until we fix the appt2 command, I have removed the aapt2 paths from aapt.vim and it now looks like below

```
  let l:aapt_paths = [
        \ android#buildToolsPath() . '/aapt',
        \ 'aapt',
        \ '/bin/false'
        \ ]
```

deleted lines

```
        \ android#buildToolsPath() . '/aapt2',
        \ 'aapt2',

```

**Comment by hsanson** [comment]
Can you check if #106 that was recently merged solves this problem for you?

**Comment by sultanahamer** [comment]
@hsanson #106 isn't working for me. I think there is some extra character coming after the file name in the logic. May be the contributor tested in a different operating system. I am using mac as of now. Below is the error message I am facing right now

```
Error detected while processing function <SNR>202_on_exit[4]..Callback:
line    9:
E484: Can't open file /Users/sultanm/Projects/OpenContacts/app/build/outputs/apk//release/output-metadata.json/Users/sultanm/Proje
cts/OpenContacts/app/build/outputs/apk//debug/output-metadata.json^@
```

**Comment by DonnieWest** [comment]
@sultanahamer doesn't look like an alternative OS, it looks like you have both release and debug metadata. That's not something I accounted for

Could you send over the directory structure and files in  `/Users/sultanm/Projects/OpenContacts/app/build/outputs/apk`? I typically use `tree` to get that information

Looks like I need an additional if statement or two to handle those cases as well

**Comment by sultanahamer** [comment]
I have fixed it, sending a pr right away

**Comment by sultanahamer** [comment]
Also l:name is empty always. My command for install is 

:AndroidLaunch debug

**Comment by DonnieWest** [comment]
yep, I didn't account for:

* Apps without variants/flavors
* Launching both release and debug versions of the app

I'm pretty sure I have a fix already, I just wanted to make sure it worked with your directory structure too :P

**Comment by sultanahamer** [comment]
@DonnieWest here is the directory structure.

<img width="345" alt="image" src="https://user-images.githubusercontent.com/11389059/152658190-1c3a8df8-b652-444d-ae48-929a6565e619.png">

after removing multiple flavor apk and having single apk also failed with '^@' character at end of filename. so thought will change the |tr |sed part to something else.

**Comment by DonnieWest** [comment]
#108 how's that?

I tested it against OpenContacts and that seemed to do the trick, but I still need to test it against multi variant projects

**Comment by DonnieWest** [comment]
@sultanahamer Ah, I missed your PR fixing that newline. I'd be curious if you're still seeing that character on my branch though

**Comment by sultanahamer** [comment]
@DonnieWest After raising pr and commenting here, waited for like 10 minutes and then went to sleep. It was 2AM at that time.

**Comment by hsanson** [comment]
@sultanahamer appreciated if you can test #108 already merged.

**Comment by sultanahamer** [comment]
@hsanson as soon as I launch noevim after update, I see the following errors

```
"app/src/main/java/opencontacts/open/com/opencontacts/activities/MainActivity.java" 410L, 18120C
Error detected while processing /Users/sultanm/.config/nvim/plugged/vim-android/autoload/android.vim:
line  195:
E700: Unknown function: Callback
E700: Unknown function: Callback
E700: Unknown function: Callback
E461: Illegal variable name: l:options
line  201:
E121: Undefined variable: a:mode
line  208:
E121: Undefined variable: l:cmd
E116: Invalid arguments for function join
E116: Invalid arguments for function job#start
line  209:
E193: :endfunction not inside a function
Press ENTER or type command to continue
```

**Comment by sultanahamer** [comment]
Another issue I found here is that the Install and launch part are happening twice. Here is the message log I captured after starting neovim fresh and running :AndroidLaunch debug

```
"app/src/main/java/opencontacts/open/com/opencontacts/activities/MainActivity.java" 410L, 18120C
vim-android: Install and Launch demoDebug emulator-5554
vim-android: Installing /Users/sultanm/Projects/OpenContacts/app/build/outputs/apk//demo/debug/app-demo-debug.apk on emulator-5554

vim-android: Main opencontacts.open.com.opencontacts.demo.debug
vim-android: Launching opencontacts.open.com.opencontacts.demo.debug on emulator-5554
vim-android:
vim-android: Install and Launch demoDebug emulator-5554
vim-android: Installing /Users/sultanm/Projects/OpenContacts/app/build/outputs/apk//demo/debug/app-demo-debug.apk on emulator-5554

vim-android: Main opencontacts.open.com.opencontacts.demo.debug
vim-android: Launching opencontacts.open.com.opencontacts.demo.debug on emulator-5554
vim-android:
Press ENTER or type command to continue
```

**Comment by hsanson** [comment]
I am unable  to replicate this behavior.  Running  :AndroidLaunch demoDebug only  runs once on my setup:

```
vim-android: Install and Launch demoDebug 354962113208956
vim-android: Installing /home/myuser/Projects/HelloWorld/OpenContacts/app/build/outputs/apk//demo/debug/app-demo-debug.apk on 354962113208956
vim-android: Main opencontacts.open.com.opencontacts.demo.debug
vim-android: Launching opencontacts.open.com.opencontacts.demo.debug on 354962113208956
vim-android:
Press ENTER or type command to continue
```

Also looking at the code I see no way for this to be invoked twice.

**Comment by sultanahamer** [comment]
@hsanson tested and is working fine.

I have also tested a react native project and is working fine as well.

Only thing people from react native project should do is to open the android directory inside react native app as root in vim and setup class path etc. Once done they should be able to open project from parent react native directory and it should work fine from there on.,
