### ISSUE TITLE
Progress of commands like Gradle sync Android build

### ISSUE THREAD

**Issue by sultanahamer** [hsanson/vim-android#109]
As the title says, as a user, I don't get to know when does the build end. I currently am monitoring it through Activity monitor(mac) similar to top on linux or task manager on windows.

May be some message once the build has completed. Problem with message is that, it will be pushed away by new messages coming up.

There is a new api in neovim called vim.notify which shows notifications like regular IDEs. But it won't work for vim users. At the least please use notify api from neovim until we have something concrete for vim.

**Comment by hsanson** [comment]
You can use `lightline#gradle#running()` to check the status of the plugin (see :h vim-android-statusline).  Using this function you should be able to customize your status line so it shows if vim-android is executing or not.  See  `: h vim-android-airline` or `:h  vim-android-lightline` for examples on how to do this with airline or lightline status line plugins.

**Comment by sultanahamer** [comment]
@hsanson that should help. Will see how can I integrate with my current setup. I am thinking of some notifications/fidget 
https://github.com/j-hui/fidget.nvim
[nvim.notify](https://github.com/rcarriga/nvim-notify)

**Comment by hsanson** [comment]
Those plugins look useful...
