### ISSUE TITLE
File classpath.vim collides with tpope/vim-classpath.

### ISSUE THREAD

**Issue by xelxebar** [hsanson/vim-android#20]
## Synopsis

The file `classpath.vim` has a fairly generic name and collides with a similarly named file from the [tpope/vim-classpath](https://github.com/tpope/vim-classpath) plugin. This causes the function `classpath#setClasspath` to remain undefined, and the vim-android plugin fails to fully load.

## Reproduction

Install the [tpope/vim-classpath](https://github.com/tpope/vim-classpath) plugin and open a file from an android project.

**Comment by hsanson** [comment]
Thanks for reporting. I moved all classpath public methods to gradle name.
