### ISSUE TITLE
Classpath generation too slow....

### ISSUE THREAD

**Issue by hsanson** [hsanson/vim-android#22]
The method that sets the CLASSPATH env variable is too slow!. I need to benchmark and optimize this using caching methods etc...

**Comment by hsanson** [comment]
Maybe useful to fix this issue:

  http://stackoverflow.com/questions/12213597/how-to-see-which-plugins-are-making-vim-slow

**Comment by wsdjeg** [comment]
neovim'job feature will make it better
see https://github.com/artur-shaik/vim-javacomplete2

**Comment by hsanson** [comment]
Indeed, I am planning to use neovim async functionality when I learn how to use it.

**Comment by hsanson** [comment]
This issue will be addressed in #41...
