### ISSUE TITLE
2 issue on my mac: targetVersion like 'android-23' and R.java for syntastic

### ISSUE THREAD

**Issue by GuanDong** [hsanson/vim-android#26]
i fix them like this:

```
function! s:getProjectJar()¬                                                     
  let l:local = fnamemodify('build/intermediates/bundles/debug/classes.jar', ':p')¬
  if filereadable(l:local)¬                                                      
    return l:local¬                                                              
  else¬     
" for the classes.jar not exist, use the classes dir instead. and also the function s:getGradleSrcPaths().                                                                      
    let l:local = fnamemodify("build/intermediates/classes/debug", ':p')¬        
      if isdirectory(l:local)¬                                                     
        return l:local¬                                                            
      endif¬                                                                       
   endif¬                                                                         
endfunction
```

```
function! gradle#getTargetVersion()¬                                                                                              
   let l:androidTarget = "UNDEFINED"¬                                             
   let l:gradleFile = gradle#findGradleFile()¬                                    
   if filereadable(l:gradleFile)¬                                                 
    for line in readfile(l:gradleFile)¬                                          
      if line =~ 'compileSdkVersion'¬                                            
       let l:androidTarget = split(substitute(line, "['\"]", '', "g"), ' ')[-1]¬
       if stridx(l:androidTarget, ':') > 0¬                                     
        let l:androidTarget = split(l:androidTarget, ':')[1]¬  
" my target version is "android-23", so split by '-' to get the number       
       elseif stridx(l:androidTarget, '-') > 0¬                                 
        let l:androidTarget = split(l:androidTarget, '-')[1]¬                  
       endif¬                                                                   
      endif¬                                                                     
     endfor¬                                                                      
   endif¬                                                                         
   return l:androidTarget¬                                                        
 endfunction
```

**Comment by hsanson** [comment]
I modified the getTargetVersion() regular expression to match strings that start with "compileSdkVersion" and end with a two digit integer. This should match your case "android-23" and the full names too like "Google Inc.:Google APIs:21".  I hope this matches most user cases and solves your second issue.

With respect your first solution I really do not understand the issue. How is possible that there is no classes.jar file? As long as you compile debug that jar should exist.

If you can explain better the problem in a new issue I will try to look into it.

**Comment by GuanDong** [comment]
on my android gradle project (android create project -t 1 -n HelloVim -p hellovim -k com.gchuyun.hellovim -a HelloVim -g -v 1.3.1), the build/intermediates like this:
build/intermediates
├── assets
│   └── debug   (noting under this dir)
├── classes
│   └── debug
│       ├── android
│       │   └── support
│       │       └── v7
│       │           └── appcompat
│       │               ├── R$anim.class
│       │               ├── ......
│       │               └── R.class
│       └── com
│           └── gchuyun
│               └── hellovim
│                   ├── HelloVim.class
│                   ├── R$anim.class
│                   ├── ......
│                   └── R.class


i modify the setClasspath function in gradle.vim, set the $CLASSPATH like this.

let l:gradleFile = gradle#findGradleFile()¬                                    
 2 ¬                                                                                
 3   let l:isTaskExist = 0¬                                                         
 4   for line in readfile(l:gradleFile)¬                                            
 5   ∙ if line =~ "^task classpath << {$"¬                                          
 6   ∙ ∙ echo line¬                                                                 
 7   ∙ ∙ let l:isTaskExist = 1¬                                                     
 8   ∙ endif¬                                                                       
 9   endfor¬                                                                        
10   if l:isTaskExist == 0¬                                                         
11   ∙ silent! execute "!echo " . '"\ntask classpath << {\n\tconfigurations.compile.each { jar ->\n\t\tprint \":\${jar.path}\"\n\t}\n}"' . " >> " . l:gradleFile¬
12   ∙ exec "redraw!"¬                                                              
13   endif¬
      " get the dependencies in the build.gradle, but not exclude the *.aar                                                                         
14   let l:targetJar = gradle#getTargetJarPath()¬                                   
15 ¬ 
       " get the jar in aar and other gradle dependencies                                                                               
16   let l:buildJarList = split(system('ls ' . gradle#findRoot() . '/build/**/*.jar'), '\n')¬
17 ¬                                                                                
18   let $CLASSPATH = '.:' . gradle#findRoot() . '/build/intermediates/classes/debug:' . join(l:buildJarList, ':') . ':' . l:targetJar . system(gradle#bin() . ' -q classpath')
