### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by ElArtista** [hsanson/vim-android#27]
It would be nice if the plugin worked on windows too :(..
I'm trying to find and fix various problems of the plugin my self for now.

I so far found a hardcoded '/bin/cp' path used when copying the file that contains the vim task.
Also note that the CLASSPATH variable uses as its separator ';' instead of ':' in windows.

**Comment by hsanson** [comment]
I have made some modifications to the plugin in order to address both issues you mention.

Unfortunately I do not have access to Windows so I depend on you to test the changes.

Feel free to re-open the issue if my fixes don't work.
