### ISSUE TITLE
Proposal: Merge VimStudio and vim-android

### ISSUE THREAD

**Issue by DonnieWest** [hsanson/vim-android#28]
Hey! I'm the maintainer of VimStudio. It's another project dedicated to bringing full Android powers to Vim. I've been watching your project for a while (and stealing your Gradle compiler script) and I've loved the direction you're taking it.

The biggest thing I've noticed lately is the overlapping feature sets across our two projects: you've recently switched over to pulling all classpaths from Gradle itself using an init file, the newer linting features, etc. I think yours is the better project - it's compatible with all versions of Vim (not just Neovim like mine) and has a more mature codebase, more features, etc.

All that is to say: let's join forces. I'd like to port over features from VimStudio that you don't have:

1. Rudimentary XML completion
2. Retrieve classpaths and sourcepaths from JavaComplete2 instead of from Gradle (They currently use the gradle init file approach with FULL android support and both projects running Gradle on a file open is tedious)
3. Project creation from templates (incubating feature I've been working on)
4. Syntastic, Neomake and Accio support

I mainly put this here so I don't seem like I'm hijacking your project when I come with pull requests later. I really think vim-android has enormous potential. Feel free to reject these features if you don't think they fit in here. Please let me know what you think!

Thanks for your consideration!

**Comment by hsanson** [comment]
Great!! I am also interested in improving this plugin with the features you mention. The more I learn how to use Gradle the more features I can add. Just recently found a way to parse and output to stderr the XML reports generated by checkstyle, findbugs and pmd. This allows me now to parse these reports with vim errorformat and display them in the quickfix window. I was missing a way to configure these plugins via init gradle scripts and just found a way to do it looking at your VimStudio.gradle file, thanks.

Please note that I want to keep this plugin in vimscript only. No ruby/python/lua or similar will be accepted. Gradle init scripts can be used to overcome vimscript limitations (e.g. parsing xml).

Neovim features like async API is welcome as long as there is a graceful fallback  when the feature is not supported.

**Comment by DonnieWest** [comment]
I'll start on some vimscript only pull requests then :-)
