### ISSUE TITLE
Android project detection fails if AndroidManifest.xml has errors

### ISSUE THREAD

**Issue by hsanson** [hsanson/vim-android#32]
If the AndroidManifest.xml or any resource xml file has errors in it (e.g. wrong tags, not terminated tags, etc.) then the vim gradle task fails. This results in the android project not being detected as such and the plugin not loading correctly.

I need to find a better way to detect if a project is android project.

**Comment by DonnieWest** [comment]
What are your current thoughts on this?

The way I've been doing it in VimStudio is checking for an AndroidManifest.xml file in the current project.
