### ISSUE TITLE
Find a way to report why a gradle sync fails.

### ISSUE THREAD

**Issue by hsanson** [hsanson/vim-android#45]
Running GradleSync can fail for several reasons but currently the plugin only prints "Gradle sync task failed" in such cases. 

One way to solve this is to write the output of the sync to a file and provide a command to dump it in the quickfix window, or set an errorformat for it and show the errors.

Ideas are welcome.

This is sample ouput of a sync fail:

```
:ext:vim
vim-project ext
vim-target android-22
:ext:CircularProgressBar:vim
vim-project CircularProgressBar
vim-target android-22
:ext:CircularProgressBar:vim FAILED

FAILURE: Build failed with an exception.

* Where:
Initialization script '/home/ryujin/Projects/vim/vim-android/gradle/init.gradle' line: 15

* What went wrong:
Execution failed for task ':ext:CircularProgressBar:vim'.
> Could not resolve all dependencies for configuration ':ext:CircularProgressBar:androidJacocoAgent'.
   > Could not find org.jacoco:org.jacoco.agent:0.7.4.201502262128.
     Searched in the following locations:
         file:/home/ryujin/Apps/android-sdk/extras/android/m2repository/org/jacoco/org.jacoco.agent/0.7.4.201502262128/org.jacoco.agent-0.7.4.201502262128.pom
         file:/home/ryujin/Apps/android-sdk/extras/android/m2repository/org/jacoco/org.jacoco.agent/0.7.4.201502262128/org.jacoco.agent-0.7.4.201502262128.jar
         file:/home/ryujin/Apps/android-sdk/extras/google/m2repository/org/jacoco/org.jacoco.agent/0.7.4.201502262128/org.jacoco.agent-0.7.4.201502262128.pom
         file:/home/ryujin/Apps/android-sdk/extras/google/m2repository/org/jacoco/org.jacoco.agent/0.7.4.201502262128/org.jacoco.agent-0.7.4.201502262128.jar
     Required by:
         kidint-android.ext:CircularProgressBar:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.568 secs
```

**Comment by zhaozg** [comment]
Continues?

**Comment by hsanson** [comment]
Sorry, I am not able to add new features to this plugin. It is difficult to keep up with Android Studio and Android SDK speed. Everytime they change the gradle output the plugin breaks.

I have my hopes put on vim-ale with language server support:

  - [vim ale](https://github.com/w0rp/ale): Amazing plugin, works out of the box with most projects.
  - [IntelliJ LSP Server](https://github.com/Ruin0x11/intellij-lsp-server): Hopefully will support Android Studio. If this happens then my plugin will be obsoleted.
  - [Kotlin LSP Server](https://github.com/georgewfraser/kotlin-language-server): Works partially with android projects. For some reason does not find gradle dependencies.
  - [Java LSP Server](https://github.com/georgewfraser/vscode-javac): Works partially with android projects. Also cannot find all dependencies from gradle.
