### ISSUE TITLE
Support variants and aar dependencies

### ISSUE THREAD

**Issue by wuman** [hsanson/vim-android#47]
It appears that the `android#getProjectJar()` function assumes that all project class files are located in the `/build/intermediates/classes/debug` folder, which is not the case when the project has build variants.

Also if a dependency is an aar, the dependency's classes.jar file is not included.  These classes.jar are in the `/build/intermediates/exploded-aar/.../jars/classes.jar` directories.

I wish I could send a patch for this but unfortunately I'm not familiar with vim scripting.

**Comment by wuman** [comment]
I've attempted to add the dependency jars via #48.

**Comment by hsanson** [comment]
Support for exploded aar jar files is added in 9fd8316f3f2.
