### ISSUE TITLE
E117: Unknown function: gradle#setCompiler

### ISSUE THREAD

**Issue by robbieh** [hsanson/vim-android#50]
When I try any of the :Android commands, I get this error:
E117: Unknown function: gradle#setCompiler

However, the :Gradle commands work OK.

g:gradle_bin is set to "./gradlew"

**Comment by hsanson** [comment]
I am having trouble replicating this issue. Did you set the value for g:gradle_bin explicitly in you config or was it automatically set by the vim-android plugin?

when set automatically on my environment I can run both Gradle and Android commands without problem. In fact Android command does exactly the same a Gradle and exists only
for backward compatibility.

**Comment by robbieh** [comment]
Thanks for checking!

I don't know why, but I'm not getting the same error as before. I haven't updated plugins, so I don't understand what would be different.

I'm not setting g:gradle_bin in my .vimrc config.

Maybe I don't quite understand, but I would expect these three vim commands to be the same as running ./gradlew installDebug (which works fine):
:Gradle installDebug
:AndroidInstall debug
:Android installDebug

But they don't. Running :Gradle installDebug does not give me any output at all.
Running :AndroidInstall debug gives me this in the Vim status area:
```
Error detected while processing function android#install[13]..gradle#install:
line    3:
vim-android:

```
Yes, that's it. Nothing after vim-android: in that output.
And running :Android installDebug gives me a lot of output in the terminal:

```

* What went wrong:
Task '[installDebug]' not found in project ':app'. Some candidates are: 'installDebug', 'uninstallDebug'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

FAILURE: Build failed with an exception.

* What went wrong:
Task '[installDebug]' not found in project ':app'. Some candidates are: 'installDebug', 'uninstallDebug'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```

This is on Ubuntu 15.10. I have these plugins installed:
jedi-vim  paredit.vim  rust.vim  slimux  vim-android  vim-arduino-ino  vim-autoclose  vim-classpath  vim-clojure-static  vim-fireplace  vim-flake8  vim-hy  vim-javacomplete2  vim-racket  vim-supertab  Vundle.vim

**Comment by hsanson** [comment]
@robbieh are you using the latest master of the vim-android plugin? Anyway I will check again this weekend when I have time.

**Comment by robbieh** [comment]
Yes, I believe this is the latest:

```
[branch:master][0]
[robbie@Vermouth:~/.vim/bundle/vim-android]
[2]=> git pull
Already up-to-date.
```

**Comment by hsanson** [comment]
The command *AndroidInstall debug* was broken and that is my fault. I added a fix but I recommend you use only the Gradle command as I plan to deprecate all Android commands in the future.

The *Android installDebug* is in fact the same as *Gradle installDebug* so I find it strange that you get different output on each case. If you are using NeoVim then Gradle command will
run in the background and show no output unless there are errors. Make sure you set the g:gradle_quickfix_show variable to 1 so you get the quickfix window open in case of errors.

Run *git log* in the plugin directory and ensure you have commit: f9ba1043

Also run  *gradle installDebug* in a terminal and ensure it works there.
