### ISSUE TITLE
Android lint failing

### ISSUE THREAD

**Issue by teasp00n** [hsanson/vim-android#53]
`Android lint` appears to run `Gradle '[lint]'` which causes the following output in the quickfix list `|| Task '[lint]' not found in project ':app'. Some candidates are: 'lint'.` 

Are the `[]` added erroneously or is my setup likely at fault?

**Comment by hsanson** [comment]
I added a fix for this. Note that the Android command is there for backward compatibility and everything that can be done with it can be done with the Gradle command.

With time this plugin became more Gradle than Android so any gradle project could be developed using this plugin.
