### ISSUE TITLE
Omnicompletion not smart enough to recognize Gradle libraries

### ISSUE THREAD

**Issue by haskellcamargo** [hsanson/vim-android#54]
Hello, and congratulations for the nice plugin!

I'm using the [vim-javacomplete2](https://github.com/artur-shaik/vim-javacomplete2) plugin with the `vim-android` plugin. It works fine for common Java code, for existing symbols in **the current** class and for Android common classes. No worries.

![image](https://cloud.githubusercontent.com/assets/7553006/17312461/3a00c3ac-5829-11e6-893a-92a8f7d53c90.png)

However, although `CLASSPATH` environment variable is set for Android SDK (in my case `/home/haskell/Android/Sdk/platforms/android-23/android.jar`), it seems unable to provide information about project symbols (it works fine for importing project classes, but not for referencing methods, for example, using `C-x` `C-o`). 

I've read the [`doc/vim-android.txt`](https://github.com/hsanson/vim-android/blob/master/doc/vim-android.txt) file and it says the plugin auto populates the `CLASSPATH` variable.

Being more specific, the following gives `Pattern not found`

- Referencing project files
- Referencing library of the project files

Is there any step that I'm missing? I'm on Elementary OS, Vim 7.4 and my full `.vimrc` is [available here](https://gist.github.com/haskellcamargo/5b3906ad938220dd34cbbc408770f689). Also, I'm starting Vim with `env CLASSPATH=/home/haskell/Android/Sdk/platforms/android-23/android.jar vim` inside Fish shell and with ` CLASSPATH=/home/haskell/Android/Sdk/platforms/android-23/android.jar vim` outside it. The current value of `CLASSPATH` is empty by default.

![image](https://cloud.githubusercontent.com/assets/7553006/17312696/efaac13e-582a-11e6-862d-f1183aae60d9.png)

Thank you!

**Comment by DonnieWest** [comment]
@haskellcamargo by default, vim-android turns over classpath generation to javacomplete2. My knee jerk reaction is that overriding CLASSPATH like you are, you're disrupting javacomplete2's default behavior of pulling that CLASSPATH from gradle

If you can replicate this issue with a minimal vimrc (ie just the javacomplete2 plugin loaded while editting your project and without these outside env variables set) please open an issue over there with us :)

**Comment by haskellcamargo** [comment]
Well, with my current `.vimrc` and without any environment variable, the plugin is able to tell only local file and JDK information. Nothing about Android (that works with `env`) and the libraries.

I believe that this may have some relation with how Gradle was installed. I already had Android Studio.

I was having this error with implicit Gradle wrapper in the project:
![image](https://cloud.githubusercontent.com/assets/7553006/17313462/2ac7dc1e-5832-11e6-8f15-bef2976a8fcc.png)

So, I've installed Gradle via `apt-get`. Has this any influence of how is the `CLASSPATH` provided?

If not, I'll try with a clean `.vimrc` and only with `javacomplete2`.

**Comment by DonnieWest** [comment]
@haskellcamargo looks like there may be more to this than I thought. What happens if you run `./gradlew assembleDebug` in the root of your project?

**Comment by haskellcamargo** [comment]
![image](https://cloud.githubusercontent.com/assets/7553006/17313706/69bdd3c2-5834-11e6-8acf-f0d187aca52b.png)

Two long minutes and no single error (however, I don't know if it is correctly calling `./gradlew`, because Gradle binary is global).

**Comment by DonnieWest** [comment]
As long as you made sure to run `./gradlew`, it used the gradle wrapper. I'm not entirely sure why vim-android isn't picking it up. To get it working, I would try manually setting the location of the gradle binary like so `let g:gradle_path = /path/to/gradle/folder`

Please also let me know if you can get completions working with the minimal vimrc and without CLASSPATH set manually. I'm starting to wonder if neither plugins are picking up your gradle wrapper

**Comment by haskellcamargo** [comment]
An important detail is that `:echo $CLASSPATH` (inside vim) outputs `.:.:.`.
The error happens in 2 machines. Both use same configuration. Defining the binary for `./gradlew` doesn't work how I expect (`let g:gradle_path='./ngi/ginga-android/gradlew'`). I believe I'm doing some mistake here. Using a minimal  `.vimrc` also doesn't work as expected. Same error:

```viml
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

Plugin 'hsanson/vim-android'
Plugin 'artur-shaik/vim-javacomplete2'

" All of your Plugins must be added before the following line
call vundle#end()

" Set path for Android SDK (Android plugin)
let g:android_sdk_path='/home/haskell/Android/Sdk'
" ? let g:gradle_path='./ngi/ginga-android/gradlew'

" Java/Android omnicompletion
autocmd FileType java setlocal omnifunc=javacomplete#Complete
```

**Comment by haskellcamargo** [comment]
I believe that setting Gradle binary **might** work, but how do I set for `./gradlew` correctly?

**Comment by DonnieWest** [comment]
@haskellcamargo can you confirm that running `:pwd` shows your project root? Can you also try the minimal vimrc with JUST vim-javacomplete2 just to see if that makes a difference?

**Comment by haskellcamargo** [comment]
- `:pwd` shows my project root
- Running with just `vim-javacomplete2`, `:echo $CLASSPATH` gives empty and only the current source exports symbols.

**Comment by DonnieWest** [comment]
@haskellcamargo do you have the time to create a minimal project that I can test this against?

**Comment by haskellcamargo** [comment]
Empty project (`https://github.com/haskellcamargo/omnifunc-bug-test`).
Same problem, but now `$CLASSPATH` became `:.:.:.`. Also, was `:pwd` supposed to list my directory or my root project? It lists my directory. Should I start `vim` from root instead?

**Comment by haskellcamargo** [comment]
Well, starting `vim` from the root gives me an empty `$CLASSPATH` and nothing else, only a slower initial sync.

**Comment by haskellcamargo** [comment]
Ah, wait! The previous build was broken. When it finished, it started working! Apparently, you **MUST** start vim from the root and then open the project source. Otherwise, :hankey: happens! Thank you very much for the help, ah, I believe it would be nice to have this information in the README :smile:

**Comment by DonnieWest** [comment]
@haskellcamargo glad to have been of help :)

I can see how not starting vim from the root can be confusing, I'll see about adding it to each project's respective READMEs
