### ISSUE TITLE
Multiple Module Support

### ISSUE THREAD

**Issue by teasp00n** [hsanson/vim-android#55]
Should this support multi module projects out of the box?

Consider a project of the form:

```
build.gradle
appModule/build.gradle
coreModule/build.gradle
```

With a top level `settings.gradle` with:

```
include ':appModule', ':coreModule'
```

When I open a file in the appModule it would be ideal if the $CLASSPATH was generated by invoking gradle with the top level `build.gradle` rather than than the first `build.gradle` encountered in an 'upwards' traversal of the directories.

I modified the `autoload/gradle.vim` file slightly to allow it to do this. (I haven't used vimscript before, excuse any weirdness with my code :))

```
function! gradle#findGradleFileRecurse(path)
  let l:parent_path = fnamemodify(fnamemodify(a:path, ":h"), ":p")

  if filereadable(fnamemodify(l:parent_path, ":p")."build.gradle")
    return gradle#findGradleFileRecurse(fnamemodify(l:parent_path, ":p:h"))
  else
    return a:path
  endif
endfunction
```

This function is called with the path found by the initial traversal:

```
let l:file = findfile("build.gradle", l:path . ";$HOME")
let l:file = gradle#findGradleFileRecurse(fnamemodify(l:file,":h"))
```

In essence, it will find the first `build.gradle` file and then traverse upward until it doesn't find one, returning the last one that it found. This should, in theory, be the top level `build.gradle` for the project.

If this seems reasonable to you I can tidy it up and make a PR. Any suggestions also welcome.

**Comment by hsanson** [comment]
How it works now is that the dependencies for each build.gradle file are loaded and kept in a dictionary. If your gradle files contain all their dependencies then the CLASSPATH will contain only the dependencies required for the currently loaded java file and not all the dependencies of all modules in the project. 

This is desired for example if you have a project with two modules that depend on two different versions of the same library. When auto-completing you want to ensure that your CLASSPATH has the correct version of the library for the file that is being edited at the moment. Also Windows has a limit on how many chars CLASSPATH can hold so we need to load it with the bare minimum. 

The current behavior works well  but I am open to change it if there is something that is not working for you. Feel free to open a new issue if this is the case.

NOTE: if you are using javacomplete2 plugin then this functionality gets disabled and the CLASSPATH is generated by javacomplete2. I am unaware on the details of how javacomplete2 generates the CLASSPATH so better ask the author of that plugin if something is not working well for you.

**Comment by teasp00n** [comment]
Ahhh OK that makes sense. Also, I am using javacomplete2 so I'll review how the CLASSPATH is being generated there.

Thanks for your feedback :)
