### ISSUE TITLE
Plugin doesn't seem to load

### ISSUE THREAD

**Issue by JonasVautherin** [hsanson/vim-android#56]
Using dein, I can make java-complete2 work, but vim-android doesn't seem to load. `:Gradle` results in an error ("Not an editor command"). 

Is there something special to do (I mean, more than installing the plugin)? Can I verify that the plugin is loaded, somehow?

**Comment by hsanson** [comment]
The gradle plugin should load automatically when the following conditions are met:

 1. You open a java or xml file.
 2. There is a build.gradle file in your current path or parents of that path up to your HOME.
 3. The gradle binary is in your path or you have a gradlew script on the project root.

some things you can try to debug the issue:

  1. Open a java or xml file inside your project.
  2. Check that vim current path is the root path of your Gradle/Android project with  *:pwd* command.
  3. Run *:echo gradle#isGradleProject()* to see if the plugin detects the project as gradle project.
  4. If the above command returns 0 then run *:echo  gradle#findGradleFile()* to see if the plugin is finding your gradle build file.
  5. Also check if the plugin can find gradle binaries running *:echo gradle#bin()* command.

If you know vimscript you can easily check the source of these methods to see why they may be failling to detect your project as a Gradle project.

Let me know how it goes with these commands so I can try to help you get this sorted.

**Comment by JonasVautherin** [comment]
So, I have one project where autocomplete does not work for Android (it works for java, I have java-complete2 and neocomplete, I don't know if it is the right way), and `:echo gradle#...` is not defined at all.

Interestingly, I have another project where the Android autocomplete works (say I use an Android `Context`, it will be able to import it and to autocomplete it), but the gradle commands still don't exist...

I am on Arch Linux, and I have no clue about vimscript (I am really not an expert with vim plugins. I usually just install them) =/. I will try to have a look, still.

Thanks for the help!

**Comment by hsanson** [comment]
If the gradle#... commands are not defined, then the vim-android plugin is not being installed correctly on your system. I can tell vim is not loading the plugin because these gradle#... commands should be available independently of the project/file you have open.

I must also clarify that vim-android does not provide autocompletion at all. The javacomplete2 plugin does it and it should work in any project/file even without the vim-android plugin installed. 

I believe this issue is unrelated with the plugin itself so I will close it. But I would greatly appreciate you re-open the issue if you find it is actually a problem in the plugin or if you find a solution it would be nice to add additional comments so others can learn from it.

**Comment by JonasVautherin** [comment]
What I don't get is that if I remove vim-android from my .vimrc, then javacomplete stops completing the Android types. Which makes me think that the plugin is loaded, but apparently not, since the gradle commands are not defined. How can we explain that?

**Comment by hsanson** [comment]
Autocompletion in Java depends on the contents of the CLASSPATH environment variable. Both vim-android and javacomplete2 have functions that try to setup the CLASSPATH depending on the current project dependencies using gradle.

One thing you may try is to check the value of CLASSPATH using *:echo $CLASSPATH* within vim after loading a java file. Check it with and without the vim-android project to see if there are differences.

Note that vim-android checks for the presence of the javacomplete2 plugin and will not touch the CLASSPATH variable if that plugin is present. In other words the CLASSPATH you get should be the same with or without vim-android installed. If it is not then the plugins must be interfering with each other in some way.
