### ISSUE TITLE
syntastic class path not set the first time opening project *.java

### ISSUE THREAD

**Issue by IanEdington** [hsanson/vim-android#57]
When I open a *.java from a project I've never opened before, gradle sync gets called, however, the g:syntastic_java_javac_classpath variable doesn't get set to the new classpath.

This only happens for the first file I open in a project. If I `:e` a second file in the same vim instance it works, same with `:bn` back to the first file it works.

running macvim.

**Comment by hsanson** [comment]
This is a little complicated to solve when using async mode. The g:syntastic_java_javac_classpath is set before the async task completes resulting on it not being set correctly.

In fact I will remove any code that depends on other plugins (e.g. syntastic, javacomplete) and provide methods that allow easy integration instead.

**Comment by IanEdington** [comment]
ok great. Thank you. Is there a command I can run after opening that would reset the g:syntastic_java_javac_classpath once the gradlesync is finished?

**Comment by hsanson** [comment]
I added a possible fix for this. In latest version of the plugin you can call:

```
call gradle#setup()
```

to setup the CLASSPATH, SRCPATH and g:syntastic_java_javac_classpath variables.
