### ISSUE TITLE
E488: Trailing characters

### ISSUE THREAD

**Issue by kshivang** [hsanson/vim-android#59]
Got this error while running  :androidinstall debug command

Error detected while processing function android#install[6]..gradle#install:
line    3:
E488: Trailing characters

Though apk installed perfectly, but it does not auto-start.

**Comment by kshivang** [comment]
Though error is gone, but still app doesn't popup(run) automatically after installation.
Using command ":androidInstall debug"

**Comment by hsanson** [comment]
The install command has never been able to launch the application. Before it was difficult to do as you require the main activity name in order to launch it via adb.

I found a possible solution to enable this functionality so I will create a new issue for this feature.
