### ISSUE TITLE
Add launch command

### ISSUE THREAD

**Issue by hsanson** [hsanson/vim-android#60]
Would be nice if the vim-android plugin had commands to launch applications in the devices/emulators. There seems to be an easy way to do it with only the package name:

```
adb shell monkey -p {package.name.here} -c android.intent.category.LAUNCHER 1
```

sources:
  - http://stackoverflow.com/a/25398877

Thinks that need to be done:

  - Check that monkey tool compatibility. Does it work on all android versions/tools?
  - Add package name to the vim task output during gradle#sync()
  - Add commands to execute adb command to launch using the current package name.

**Comment by hsanson** [comment]
Getting all variant/flavor package names is not trivial...  I still cannot find an easy way to do this.

Some tips I have found: http://qubanshi.cc/questions/567853/getting-package-name-of-application-variant-in-gradle-plugin

**Comment by DonnieWest** [comment]
Using the Android command line tools (specifically, `apkanalyzer`), `xmlstarlet` and `fzf` I've cobbled together the following zsh function:

```
launchAPK() {
  ./gradlew assembleDebug
  adb devices -l | tail -n +2 | sed '/^\s*$/d' | awk '{ print $1, $5 }' | sed -e 's/model://g' | awk '{ print $1 }'  | fzf -1 -m | while read device; do
    adb -s $device install-multiple -r -d $(find ./ -name "*.apk" | tr "\n" " " | tr "//" "/")

    apk=$(find ./*/build/** -name "app-debug.apk")

    mainId=$(apkanalyzer manifest print $apk | xmlstarlet sel -t -c "///activity[intent-filter/action[@android:name='android.intent.action.MAIN']]" | xmlstarlet sel -t -c "string(//*[local-name()='activity']/@android:name)")

    appId=$(apkanalyzer manifest application-id $apk)

    if [ "$appId/$mainId" != "/" ]
    then
      adb -s $device shell am start -n $appId/$mainId
    fi
  done
}
```

It's super rough and dirty, but gets the job done for installing/launching debug APKs. This sort of strategy might work for this project. I'm not sure if requiring `xmlstarlet` would be acceptable though and I'm not sure how to parse XML in Vimscript
