### ISSUE TITLE
Does vim-android work with neovim?

### ISSUE THREAD

**Issue by ragner** [hsanson/vim-android#67]
I am trying vim-android with https://neovim.io/ and looks that
all Android and Gradle commans are not working but I am not getting any error message!

**Comment by hsanson** [comment]
I use exclusively neovim and this plugin was developed using neovim for the most part. So I would say it has more probability of working with neovim than vim.

Can you run :checkhealth within neovim? it may give you some idea of what is wrong. You must run this when your current dir is the root of an android project.

**Comment by ragner** [comment]
I am using Mac OS 10.12.6

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#gradle#check
========================================================================
## vim-android checks

## Gradle checks
  - OK: Gradle binary found at ./gradlew
  - OK: Gradle async mode enabled.
  - OK: Gradle daemon mode enabled.
  - INFO: Gradle version 0

## Android checks
  - OK: Android binary found at /Users/ragner/Library/Android/sdk/tools/android
  - OK: Android home set to /Users/ragner/Library/Android/sdk
  - OK: Android emulator binary found at /Users/ragner/Library/Android/sdk/tools/emulator
  - OK: Android manifest found at /Users/ragner/Workspace/GVRf/GearVRf/GVRf/Framework/framework/src/main/AndroidManifest.xml
  - INFO: Configured glyps:
    android glyph: A
    gradle glyph:  G
    error glyph:   E
    warning glyph: W
    building glyph: building...

## ADB checks
  - OK: ADB binary found: /Users/ragner/Library/Android/sdk/platform-tools/adb

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $COLORTERM=''
  - INFO: $SSH_TTY=''

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.14
  - INFO: python2-neovim version: 0.2.4
  - OK: Latest python2-neovim is installed: 0.2.4

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3
  - INFO: Other python executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.4
  - INFO: python3-neovim version: 0.2.4
  - OK: Latest python3-neovim is installed: 0.2.4

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.7.1

## Node provider (optional)
  - WARNING: `node` and `npm` must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` commands work.

**Comment by ragner** [comment]
I am trying `:Gradle assembleDebug` but I get no message.

**Comment by ragner** [comment]
I got this at bash:
```

[ragner@SW-RAGNERN Framework (master)]$ nvim framework/src/main/java/org/gearvrf/GVRSceneObject.java                                                                                                                                                                         
Error detected while processing function <SNR>41_runHandler:
line    3:
E40: Can't open errorfile /var/folders/s6/9z0gjkcs7sq4lf20w8kvx26w0000gn/T/nvimL3mXsl/1
```

**Comment by ragner** [comment]
```
$ nvim -v
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180209-66903-ukwirj/neovim-0.2.2/build/config -I/tmp/neovim-20180209-66903-ukwirj/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180209-66903-ukwirj/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20180209-66903-ukwirj/neovim-0.2.2/build/include
Compiled by brew@Sierra-2.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2_1/share/nvim"

Run :checkhealth for more info

```

**Comment by hsanson** [comment]
Two things may be happening:

 1. The build is running in background as expected.
 2. The gradle sync() failed for some reason.

Case #1: The plugin use background jobs to do the building so no messages or errors means everything is good. You can check this by breaking your code on purpose and run "Gradle assembleDebug" again. This time the build should fail and the quickfix window should open with the build errors.

Case #2: Run the sync command directly "GradleSync" and see if it fails. Unfortunately gradle is extremely flexible and is possible my sync code is failing for your project. Here I would need your help to find out what the problem is.

First run this command within neovim:

   :echo gradle#syncCmd()

This will output the command the plugin uses to sync the project. Copy the full command and run it in a shell within the root of the project. The command looks similar to the one below, path will differ on your environment:

    ./gradlew -b /home/Projects/you-project/app/build.gradle -I /home/ryujin/Projects/vim/vim-android/gradle/init.gradle vim

Take note of any errors and try to fix them. Or send them to me and maybe I can try to find out the issue. There is no guarantee I will be able to get this working for your project/environment.

Also try disabling daemon mode (e.g. set g:gradle_daemon = 0) that seems to have some problems on latest versions of gradle.
