### ISSUE TITLE
Integration with ale and YouCompleteMe

### ISSUE THREAD

**Issue by Sammyalhashe** [hsanson/vim-android#68]
Is there a way to get vim-android configured to wrk with ale and YCM? As seen in the screen-grab below, ale is giving me errors because it has no idea what the android packages are. Also, I have java autocompletion set for YouCompleteMe. In the docs, you mention javacompleter2, but since I have YCM I'd rather stick with that.

When I enter an android project, gradle build does start, and it appears that some downloading appears to occur, so I know that vim-android is working for me on a base level. The only configuration I have for using this plugin was to set the absolute path to the android sdk with `let g:android_sdk_path=/Users/<username>/Library/Android/sdk`. I hope I did that right haha

<img width="1440" alt="screen shot 2018-05-11 at 11 17 31 pm" src="https://user-images.githubusercontent.com/20797997/39954276-9349d7cc-5571-11e8-99a0-f1658a78807e.png">

Love the work done on this btw! It gives me great satisfaction when I open and android project and the plugin starts a build.

**Comment by hsanson** [comment]
I am glad this plugin is useful to others and thanks for letting me know how it works for you.

This plugin does not try to do anything related with autocompletion or linting. These are already handled by other plugins that do a better job than what I could do. The plugin simple sets the CLASSPATH environment variable so these plugins can find the needed class files.  You can check it is being set by inspecting it within vim (e.g. :echo $CLASSPATH).

If YCM and ALE plugins honor the CLASSPATH variable then they should work. I noted that java support for YCM is marked experimental and ALE docs on java are really lacking do I would recommend that you get these plugins working first without vim-android and then add vim-android to the mix. If YCM and ALE stop working when adding vim-android then there may be some conflict between the plugins that must be investigated.

Finally I would like to mention that this plugin does not automatically builds the project. It simply synchronizes it by running a custom "gradle vim" task. To build and install the project you must use the Gradle command withing vim (e.g.  Gradle assembleDebug).
