### ISSUE TITLE
Bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by wzieba** [hsanson/vim-android#69]
Hi, am I missing something or it's known issue? When I try to run any `:Gradle` command I get

`/bin/bash: /Users/username/.vim/bundle/vim-android/tools/efmsanity: /bin/sed: bad interpreter: No such file or directory`

part of my `.vimrc`:
`let g:android_sdk_path = '/usr/local/Caskroom/android-sdk/3859397'
let g:gradle_path = '/usr/local/Cellar/gradle/4.7'`

The gradle path is correct.

**Comment by hsanson** [comment]
Difficult to know what the issue could be. It may be possible that the version of sed or bash on your system are causing issues.

For reference these are the versions I have:

```
[~]> /bin/bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

```
[~]> /bin/sed --version
/bin/sed (GNU sed) 4.2.2
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jay Fenlason, Tom Lord, Ken Pizzini,
and Paolo Bonzini.
GNU sed home page: <http://www.gnu.org/software/sed/>.
General help using GNU software: <http://www.gnu.org/gethelp/>.
E-mail bug reports to: <bug-sed@gnu.org>.
Be sure to include the word ``sed'' somewhere in the ``Subject:'' field.
```

Also if you are running neovim it would be good to run the :checkhealth command to see if there are configuration issues.
