### ISSUE TITLE
Syntastic integration

### ISSUE THREAD

**Issue by hsanson** [hsanson/vim-android#7]
I would like to write a syntastic syntax checker that gets loaded by this plugin if the syntastic plugin is detected.

This syntastic plugin should run the android linter and then compile the ant/gradle project so syntastic reports issues in the source.

**Comment by rgrinberg** [comment]
+1 This would be awesome

**Comment by dambrisco** [comment]
@hsanson I've added rough syntastic support to my fork [here](https://github.com/dambrisco/android.vim/blob/master/autoload/android.vim#L43). It relies on code being in a git repo and I'm sure there's generally a better way to do it, but I just thought I'd share.

**Comment by hsanson** [comment]
I implemented functionality similar to syntactic in the plugin itself. Still simple and may need more work but works for me. See commit 4bb4e559295ac1709643790a4c5366d93618c59b for details.
