### ISSUE TITLE
ALE intergration, possible plugin load order issue

### ISSUE THREAD

**Issue by GrimKriegor** [hsanson/vim-android#74]
Moved from https://github.com/w0rp/ale/pull/2600#issuecomment-504022105

(snip)
It would appear `vim-android` is being loaded before `ALE`, making `s:LoadedAle()` return false and preventing the whole configuration push from `vim-android` to `ALE`.
`autoload/ale_linters/java/javalsp.vim:31`
Other functionalities like registering the new `android linter` seem to be working just fine.

**:ALEInfo**
```
(snip)
Available Linters: ['android', 'checkstyle', 'eclipselsp', 'javac', 'javalsp', 'pmd']
(snip)
```

**:scriptnames**
```
(snip)
 72: ~/.vim/pack/plugins/start/vim-android/after/ftplugin/java.vim
[the other vim-android scripts]
(snip)
 80: ~/.vim/after/ftplugin/java.vim
 81: /usr/share/vim/vim81/indent/java.vim
 82: ~/.vim/pack/plugins/start/ale/autoload/ale.vim
[the other ale scripts]
(snip)
```

I believe this is caused by the way/order Vim's native plugin management chooses to source the plugins and config files.
Will report back once I find a way around this.
(snip)

------

I believe my initial assessment was incorrect.

My configuration was responsible for making `LoadedAle()` fail as I chose to declare `ale_linters` not only in `.vim/after/ftplugin/java.vim`, which loads after `vim-android` but also with buffer scoping instead of global. So that I can [run some logic](https://github.com/GrimKriegor/dotfiles/blob/519d52b5b11283775dfbf15f2daa78b99b82100d/.vim/after/ftplugin/java.vim#L8) to switch from `javalsp` to `eclipselsp` when not editing an Android project, as `javalsp` [doesn't support Gradle yet](https://github.com/georgewfraser/java-language-server/issues/98).

Moving it to `.vimrc` and scoping it globaly allows `LoadedAle()` to return true.

However, it appears something else is missing, as after Gradle syncs, no completion for Android or third party libs is available, until I run `:call ale_linters#java#javalsp#NotifyConfigChange()` manually.

I will keep this discussion up to date as I try to find out what I am missing.

Thank you for your time and effort!

**Comment by GrimKriegor** [comment]
@hsanson thanks for the detailed response @ https://github.com/w0rp/ale/pull/2600#issuecomment-504073704
Please allow me to reply here instead.

Currently when I open a `.java` file, `vim-android`'s Gradle sync message appears in the bottom, blocking Vim for a second.
Shortly after error signs from ALE appear in the gutter wherever third party or Android library symbols are present. 
The same as when running `javalsp` without populating its `classPath` array.

I believe GradleSync finishes before ALE loads, that is, if GradleSync really is blocking Vim.

```
call ch_logfile(expand('~/vimch.log'), 'w')
tail -f ~/vimch.log | grep didChangeConfiguration
```

The output of the channel log at this point in time shows a message with an empty `classPath`.
```
(snip)
{"method":"workspace/didChangeConfiguration","jsonrpc":"2.0","params":{"settings":{"java":{"externalDependencies":[],"classPath":[]}}}}'
```

However if I run one of the following commands:
```
:call ale_linters#java#javalsp#NotifyConfigChange()
(or)
:call gradle#sync()
(or)
:GradleSync
```

The gutter signs disappear, completion starts working and the channel log displays a similar message, but with a populated `classPath`.

The same happens every subsequent time I run any of those commands.

```
{"method":"workspace/didChangeConfiguration","jsonrpc":"2.0","id":2,"params":{"settings":{"java":{"externalDependencies":[],"classPath":["/home/grim/.gradle/caches/transforms-2/files-2.1/c816a9e735cd00663c00f5944e6fa312/jars/classes.jar","/home/grim/.gradle/caches/transforms-2/files-2.1/b98986f42e1ae25218a44745a3db5773/jars/classes.jar", (snip)
```

Sync command seems healthy.

**:echo gradle#syncCmd()**
```
(snip)/android-architecture-components/BasicRxJavaSample/gradlew -b (snip)/android-architecture-components/BasicRxJavaSample/app/build.gradle -I ~/.vim/pack/plugins/start/vim-android/gradle/init.gradle vim 2>&1
```

And my previous configuration, mentioned in https://github.com/w0rp/ale/pull/2600#issuecomment-503548930
Of running the LoadDeps function which runs gradle#sync() from **java.vim** still works.

Thank you for your time, and forgive me if this is just a horrible configuration issue on my part.

**Comment by hsanson** [comment]
@GrimKriegor thanks for the information. I implemented async job processing in Vim  now and during the development I found lots of things that were not working correctly  for vim but were ok in neovim.

I have fixed and reworked a lot of the plugin to make it work with vim the same way it does with neovim.

Please test the latest master and let me know if you still have issues. Your feedback has been invaluable in getting this plugin in good shape.

**Comment by GrimKriegor** [comment]
Oh damn. @hsanson you are a productivity machine!

As of https://github.com/hsanson/vim-android/commit/d0458b1cb795c8f69476c24b3f027be3f852653b and https://github.com/w0rp/ale/commit/65ba4b85ec3011cccb9ea7135183e7fc8d7a0d69 everything seems to be working wonderfully.

Whenever I open an Android Java project, Gradle sync runs in the background, ALE loads and whenever the sync finishes, ALE completion for Android and third party libs becomes available.

All that with minimal configuration:

[~/.vimrc](https://github.com/GrimKriegor/dotfiles/blob/master/.vimrc)
```
let g:android_sdk_path = expand("$ANDROID_HOME")
let g:gradle_loclist_show = 0
let g:gradle_show_signs = 0
```

[~/.vim/after/ftplugin/java.vim](https://github.com/GrimKriegor/dotfiles/blob/master/.vim/after/ftplugin/java.vim)
```
let g:ale_linters = {'java': split('checkstyle' . ' ' . system("get-java-project-linter"))}
let g:ale_java_eclipselsp_config_path = expand("$HOME") . '/.jdtls'
let g:ale_java_javalsp_executable = 'java-language-server'
```

I will be working with `vim-android` during the afternoon and will either report back if any issues arise or close this issue otherwise.

I owe you a great debt for allowing me to use the ultra comfy Vim on Android projects.

Thanks a lot!!
