### ISSUE TITLE
unknown function lightline#gradle#running

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [hsanson/vim-android#78]
I partially solved this with pull request [77][4]
I tried to configure airline as by the help file. I have environment variable 

```
export ANDROID_HOME=$HOME/Android/Sdk
```

and vimrc settings

```
" vim-android
let g:gradle_bin="/usr/bin/gradle"
let g:gradle_glyph_gradle='U+e73a'
let g:gradle_glyph_android='U+f17b'
let g:android_airline_error_glyph='U+f06a'
let g:gradle_glyph_warning='U+f071'
let g:gradle_glyph_building='U+f253'
call airline#parts#define_function(
   \ 'gradle-running',
   \ 'ligthline#gradle#running'
   \)

call airline#parts#define_function(
   \ 'gradle-errors',
   \ 'ligthline#gradle#errors'
   \)

call airline#parts#define_function(
   \ 'gradle-warnings',
   \ 'ligthline#gradle#warnings'
   \)

call airline#parts#define_function(
   \ 'gradle-project',
   \ 'ligthline#gradle#project'
   \)

let g:airline_section_x= airline#section#create_right([
 \ 'gradle-running',
 \ 'gradle-errors',
 \ 'gradle-warnings'
 \])
```
but the gradle functions `lightline#gradle#errors` or `lightline#gradle#warnings` are unknown.

I noticed that you depracted those methods [here][1]. I also read this [gradle issue][2] and configured my `g:gradle_path`.

as your file includes the function [`gradle#running`][3], I tried to set it like that, but it still triggers the same errors

I am available to assist you 
Thanks a lot
Best Regards
Fabrizio Bertoglio

[1]: https://github.com/hsanson/vim-android/blob/master/autoload/gradle.vim#L303-L311
[2]: https://github.com/hsanson/vim-android/issues/50
[3]: https://github.com/hsanson/vim-android/blob/master/autoload/gradle.vim#L317-L319
[4]: https://github.com/hsanson/vim-android/pull/77

**Comment by hsanson** [comment]
@fabriziobertoglio1987 thanks for finding the missing ' in the docs. That needs to be fixed.

Regarding the lightline#gradle#...  methods, these are still there  and not deprecated. What I deprecated was the gradle#statusLine() method.

I can run all lightline methods find without problems:

```
:echo lightline#gradle#errors()
```

These should not be removed as some people may still depend on them.

**Comment by fabriziobertoglio1987** [comment]
```zsh
➜  advanced git:(feat/fps-prop-android) ✗ vim
Error detected while processing /home/fabrizio/.dotfiles/vimrc:
line  192:
E117: Unknown function: lightline#parts#define_function
Press ENTER or type command to continue
```

I believe the issue is that you can not use [lightline][1] functions with [airline][2]. Thanks a lot

[1]: https://github.com/hsanson/vim-android/blob/master/autoload/lightline/gradle.vim#L5-L25
[2]: https://github.com/vim-airline/vim-airline/blob/master/t/section.vim

**Comment by hsanson** [comment]
These are functions, therefore must be called as such:

> :echo lightline#gradle#errors()   <-  the () is necessary

Is been long since I used airline, currently I use ligthline that uses the exact same functions to show the status.

I looked briefly into airline and is clear that the methods I used before, and documented here, are no longer available. Instead is necessary to create an airline extension to get this working. I will create an issue for this but do not think I will work on this anytime soon.

**Comment by fabriziobertoglio1987** [comment]
Thanks a lot
Bye 
Fabrizio

**Comment by fabriziobertoglio1987** [comment]
Thanks a lot

The library seems really awesome and the potential of using vim-android are endless. It blows my mind ...

so hopefully I ll have some free time to work on this, but currently I am very busy working on other PR and I am not a vim expert ...

Thanks
I wish you a good day
Fabrizio
