### ISSUE TITLE
:AndroidInstall debug/release does nothing

### ISSUE THREAD

**Issue by JartX** [hsanson/vim-android#81]
My android part of .vimrc 

let g:android_sdk_path = expand("$ANDROID_HOME")
 let g:gradle_loclist_show = 0
let g:gradle_show_signs = 0
augroup GradleGroup
autocmd!
au BufWrite build.gradle* call gradle#sync()
augroup END

**Comment by JartX** [comment]
Any have idea?

**Comment by hsanson** [comment]
Please try with latest master version of the plugin. There was some bug in how the async tasks were invoked.

**Comment by JartX** [comment]
> Please try with latest master version of the plugin. There was some bug in how the async tasks were invoked.
Solved! Any way to donate you?  :D

**Comment by hsanson** [comment]
> > Please try with latest master version of the plugin. There was some bug in how the async tasks were invoked.
> > Solved! Any way to donate you?  :D

Thanks, the best way you can donate to the project is using it and letting me know any issues you find.
