### ISSUE TITLE
:AndroidEmulator does not launch adb emulated device

### ISSUE THREAD

**Issue by lanierc** [hsanson/vim-android#86]
I have attempted several times to launch an emulator using the :AndroidEmulator command. While it will show a device list, when I type a number and hit enter as advised, the emulator does not launch. This of course does not allow me to install onto Android because it does not view the emulator as running.

For reference, I'm on macos Big Sur using kitty as my terminal, if any of that makes any difference. I do have my android sdk path set in my config, and my adb is within the normal params of that path.

(This is probably just something additional I need to do, however I haven't seen anything extra I should be doing within the readme)

**Comment by hsanson** [comment]
I would need some help to find out what the problem may be.  Can you please perform these steps:

1. Open a source file from an android project.
2. Execute this command `echo android#avds()` 
3. You should get an array with the list of defined emulators (e.g. ['0.     Pixel_2_API_30'])
4. Take note of the emulator name (e.g. Pixel_2_API_30)
5. Run this command and take note of the output `:echo android#emulatorbin()`
6. Finally run the following command using the output of emualtorbin() as executable:

> /path/to/emulator  -avd  Pixel_2_API_30  

Make sure to replace Pixel_2_API_30 with the actual emulator name you get from android#avds() method.

This should give you some idea of why the emulator is not starting in your environment.

**Comment by lanierc** [comment]
On step 2, I'm receiving: `E121: Undefined variable: android`

**Comment by hsanson** [comment]
Difficult to tell.... what do you get when executing these?

1. `:echo android#homePath()`
2. `:echo android#bin()`

**Comment by lanierc** [comment]
For 1: `/Users/coreylanier/Library/Android/sdk`
For 2: `/Users/coreylanier/Library/Android/sdk/tools/android`

**Comment by hsanson** [comment]
From what  I see it seems the plugin is working properly. Maybe the output of the android tool is not what the plugin expects.  Can you run this command and post the output:

```
:echo system(android#bin() . " list avd")
```

If you can execute manually all the steps on the android#avds() function maybe we can see what is failing on your environment.

**Comment by lanierc** [comment]
Here's what I got:

```
*************************************************************************                                                              
The "android" command is deprecated.                                                                                                   
For manual SDK, AVD, and project management, please use Android Studio.                                                                
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager                                                              
*************************************************************************                                                              
Running /Users/coreylanier/Library/Android/sdk/tools/bin/avdmanager list avd                                                           
                                                                                                                                       
Parsing /Users/coreylanier/Library/Android/sdk/build-tools/28.0.3/package.xmlParsing /Users/coreylanier/Library/Android/sdk/build-tools
/29.0.2/package.xmlParsing /Users/coreylanier/Library/Android/sdk/build-tools/30.0.2/package.xmlParsing /Users/coreylanier/Library/Andr
oid/sdk/build-tools/30.0.3/package.xmlParsing /Users/coreylanier/Library/Android/sdk/emulator/package.xmlParsing /Users/coreylanier/Lib
rary/Android/sdk/extras/intel/Hardware_Accelerated_Execution_Manager/package.xmlParsing /Users/coreylanier/Library/Android/sdk/patcher/
v4/package.xmlParsing /Users/coreylanier/Library/Android/sdk/platform-tools/package.xmlParsing /Users/coreylanier/Library/Android/sdk/p
latforms/android-29/package.xmlParsing /Users/coreylanier/Library/Android/sdk/platforms/android-30/package.xmlParsing /Users/coreylanie
r/Library/Android/sdk/sources/android-29/package.xmlParsing /Users/coreylanier/Library/Android/sdk/sources/android-30/package.xmlParsin
g /Users/coreylanier/Library/Android/sdk/system-images/android-30/google_apis/x86/package.xmlParsing /Users/coreylanier/Library/Android
/sdk/system-images/android-30/google_apis_playstore/x86/package.xmlParsing /Users/coreylanier/Library/Android/sdk/tools/package.xmlAvai
lable Android Virtual Devices:                                                                                                         
                                                                                                                                       
The following Android Virtual Devices could not be loaded:                                                                             
    Name: Pixel_4_XL_API_30                                                                                                            
    Path: /Users/coreylanier/.android/avd/Pixel_4_XL_API_30.avd                                                                        
   Error: Google pixel_4_xl no longer exists as a device                                                                               
---------                                                                                                                              
    Name: Pixel_3a_XL_API_30                                                                                                           
    Path: /Users/coreylanier/.android/avd/Pixel_3a_XL_API_30.avd                                                                       
   Error: Google pixel_3a_xl no longer exists as a device 
```

However, launching from Android Studio works perfectly fine.

**Comment by hsanson** [comment]
I am afraid this is not something this plugin can fix.  I did several experiments and looked around google and the only thing I could do was delete those AVDs and re-recreate them.

To delete them simply run these command:

```
avdmanager delete avd -n Pixel_4_XL_API_30
avdmanager delete avd -n Pixel_3a_XL_API_30
```

Then re-create them using android studio to see if this helps.

**Comment by hsanson** [comment]
On further inspection and testing I found out that the emulator binary in latest SDK has changed. I did several modifications to the AndroidEmulator command. Please use latest master and check if it works better now.

**Comment by lanierc** [comment]
Confirmed working after updating the plugin to most recent commits!

Thanks!
