### ISSUE TITLE
Unknown function:  ligthline#gradle#running

### ISSUE THREAD

**Issue by JartX** [hsanson/vim-android#88]
Hi! Any idea about it?

**Comment by JartX** [comment]
My init.vim 
https://pastebin.com/HrGNhQ6k

**Comment by JartX** [comment]
health#gradle#check
========================================================================
## vim-android checks

## Gradle checks
  - OK: Gradle binary: /home/jart/DEV/MEDYP/mesotreat_android_appv1/gradlew
  - OK: Gradle version 6.7
  - OK: Gradle async mode enabled.
  - OK: Gradle daemon mode enabled.

## Android checks
  - OK: Android home set to /home/jart/Android/Sdk
  - OK: Android emulator binary found at /home/jart/Android/Sdk/emulator/emulator
  - OK: Android manifest found at /home/jart/DEV/MEDYP/mesotreat_android_appv1/app/src/main/AndroidManifest.xml

## ADB checks
  - OK: ADB binary found: /home/jart/Android/Sdk/platform-tools/adb

**Comment by hsanson** [comment]
Swap the "h" and "t" of "ligthline" in your configuration.

**Comment by JartX** [comment]
> Swap the "h" and "t" of "ligthline" in your configuration.

Thanks for your answer @hsanson , if i do AndroidBuild it launch GradleBuild, but it doesnt do anything, any idea about it? i want to use your plugin to dev android apps on arm64 system, because android studio not work and vscode is really slow (i am testing on  x86-64 now)

**Comment by JartX** [comment]
> Swap the "h" and "t" of "ligthline" in your configuration.

Also want to donate you for your work on this plugin, but i dont view any way
