### ISSUE TITLE
apkanalyzer and openjdk+8 obsolete

### ISSUE THREAD

**Issue by JartX** [hsanson/vim-android#92]
Hi! that lines doesnt dont work because now are working with openjdk 11: 

let l:mainId = system('apkanalyzer manifest print ' . l:apk .  ' | xmlstarlet sel -t -c "///activity[intent-filter/action[@android:name=''android.intent.action.MAIN'']]" | xmlstarlet sel -t -c "string(//*[local-name()=''activity'']/@android:name)"')

  let l:appId = system('apkanalyzer manifest application-id ' . l:apk . ' | tr "\n" " " | tr "//" "/" | xargs echo -n')

Any way to change it to use a: adb shell monkey -p com.myapp.Testlag -c android.intent.category.LAUNCHER 1

**Comment by hsanson** [comment]
Solved with #93
