### ISSUE TITLE
[Java 32] [W] MainActivity.java is not on the classpath of project app, only syntax errors are reported

### ISSUE THREAD

**Issue by JartX** [hsanson/vim-android#94]
Any way to fix it?
can it be a problem of the init script?
I have tried to gradlew clean and nothing also have removed .settings

My .classpath: 
https://pastebin.com/3vSx2j3q

**Comment by hsanson** [comment]
This error is not generated by this plugin AFAIK.  Can you detail how you get this error and where?

**Comment by sultanahamer** [comment]
@hsanson @JartX after generating classpath, restart nvim so that a new jdtls server gets spawned by vim and can identify the classpath file. And from then on, it works alright.

**Comment by hsanson** [comment]
Can confirm that after generating the classpath file and restarting the eclipse instance this error dissapears.  Would really like to see some way to dynamically update eclipselsp dependencies without restarting it similar to how java-language-server allows.

Already asked in eclipse JDT but seems this is not supported:  https://github.com/eclipse/eclipse.jdt.ls/issues/1859
